### PR TITLE
fix: allows the user to pass in non-enumerated values

### PR DESCRIPTION
**Pull request by Kassell**
## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

### CODE REVIEW

**Comment by Kassell** [comment]
Using an enumeration to define options prevents the user from passing in non-enumerated values

**Comment by kirklin** [comment]
Thank you for submitting the PR and for your efforts to improve the project! We greatly appreciate your contribution to the code.

we have adopted a more optimal approach to handle union types, ensuring that the code remains flexible while enhancing readability and type safety.

You can see the changes in this commit: [1219854](https://github.com/kirklin/postcss-px-conversion/commit/12198545430d6034f1d8fa8f969620524872bdbd).

**Comment by Kassell** [comment]
> 感谢您提交 PR 并为改进项目所做的努力！我们非常感谢您对代码的贡献。
> 
> 我们采用了一种更优化的方法来处理联合类型，确保代码保持灵活性，同时增强了可读性和类型安全性。
> 
> You can see the changes in this commit: [1219854](https://github.com/kirklin/postcss-px-conversion/commit/12198545430d6034f1d8fa8f969620524872bdbd).

Have you considered what happens when users need to input values that aren't defined in the enumeration? Users would have to modify constants.ts in node_modules/postcss-px-conversion, or are you aware that enumeration classes cannot be inherited by other external classes, meaning that if users create a new enumeration and want to reference members of the old enumeration

**Comment by kirklin** [comment]
> > 感谢您提交 PR 并为改进项目所做的努力！我们非常感谢您对代码的贡献。
> > 
> > 我们采用了一种更优化的方法来处理联合类型，确保代码保持灵活性，同时增强了可读性和类型安全性。
> > 
> > You can see the changes in this commit: [1219854](https://github.com/kirklin/postcss-px-conversion/commit/12198545430d6034f1d8fa8f969620524872bdbd).
> 
> Have you considered what happens when users need to input values that aren't defined in the enumeration? Users would have to modify constants.ts in node_modules/postcss-px-conversion, or are you aware that enumeration classes cannot be inherited by other external classes, meaning that if users create a new enumeration and want to reference members of the old enumeration

The union type solves this problem
(string & object);

**Comment by Kassell** [comment]
> > > 感谢您提交 PR 并为改进项目所做的努力！我们非常感谢您对代码的贡献。
> > > 我们采用了一种更优化的方法来处理联合类型，确保代码保持灵活性，同时增强了可读性和类型安全性。
> > > You can see the changes in this commit: [1219854](https://github.com/kirklin/postcss-px-conversion/commit/12198545430d6034f1d8fa8f969620524872bdbd).
> > 
> > 
> > Have you considered what happens when users need to input values that aren't defined in the enumeration? Users would have to modify constants.ts in node_modules/postcss-px-conversion, or are you aware that enumeration classes cannot be inherited by other external classes, meaning that if users create a new enumeration and want to reference members of the old enumeration
> 
> The union type solves this problem (string & object);
Perhaps you forgot to update your npm package. I noticed that the npm package has been updated.

**Comment by Kassell** [comment]
> > > 感谢您提交 PR 并为改进项目所做的努力！我们非常感谢您对代码的贡献。
> > > 我们采用了一种更优化的方法来处理联合类型，确保代码保持灵活性，同时增强了可读性和类型安全性。
> > > You can see the changes in this commit: [1219854](https://github.com/kirklin/postcss-px-conversion/commit/12198545430d6034f1d8fa8f969620524872bdbd).
> > 
> > 
> > Have you considered what happens when users need to input values that aren't defined in the enumeration? Users would have to modify constants.ts in node_modules/postcss-px-conversion, or are you aware that enumeration classes cannot be inherited by other external classes, meaning that if users create a new enumeration and want to reference members of the old enumeration
> 
> The union type solves this problem (string & object);

I worked all day on Friday, and when I woke up on Saturday, I saw the notification that my PR was closed, which was a bit disappointing. I didn't pay too much attention to your reply at the time, and I'm very sorry for that. I see that the npm package has been updated 13 hours ago with a more elegant solution. That's great. I sincerely apologize for this.

**Pull request closed without merging**
